DROP FUNCTION IF EXISTS app.current_user_id();
DROP FUNCTION IF EXISTS app.current_tenant();
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS esg CASCADE;
DROP SCHEMA IF EXISTS app CASCADE;


