DROP TABLE IF EXISTS esg.brsr_core_kpis;
DELETE FROM esg.compliance_rules WHERE code LIKE 'BRSR-P%';
ALTER TABLE esg.compliance_rules DROP COLUMN IF EXISTS principle;
ALTER TABLE esg.compliance_rules DROP COLUMN IF EXISTS brsr_section;
DELETE FROM esg.metrics WHERE code IN ('FUEL_KG','PROCESS_EMIS','WATER_KL','WASTE_MT','WASTE_RECYCLED','EMPLOYEE_COUNT','FEMALE_PCT','SAFETY_INCIDENTS','TRAINING_HRS','MINIMUM_WAGE_PCT','CSR_SPEND','ENERGY_INTENSITY','SUPPLIER_SCREEN','CONSUMER_COMPLAINTS');
